version: "3.9"

services:
  app:
    image: ${DOCKER_IMAGE}:latest
    restart: always
    environment:
      - ENV=production
    env_file:
      - .env
    volumes:
      - ~/apps/wb_profit/:/app/data

volumes:
  wb_data:
