"""users managment

Revision ID: 77c4bc896672
Revises:
Create Date: 2025-10-09 21:12:48.104049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import models

# revision identifiers, used by Alembic.
revision: str = "77c4bc896672"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_chat_id"), "chats", ["chat_id"], unique=True)
    op.create_table(
        "scripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name_en", sa.String(length=255), nullable=False),
        sa.Column("wb_token", models.EncryptedString(), nullable=True),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    op.create_table(
        "user_script_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("enabled_until", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("report_spreadsheet_key", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["script_id"], ["scripts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "script_id", name="uq_user_script_unique"),
    )
    op.create_index("ix_links_chat", "user_script_links", ["chat_id"], unique=False)
    op.create_index(
        "ix_links_enabled_until", "user_script_links", ["enabled_until"], unique=False
    )
    op.create_index("ix_links_script", "user_script_links", ["script_id"], unique=False)
    op.create_index("ix_links_user", "user_script_links", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_links_user", table_name="user_script_links")
    op.drop_index("ix_links_script", table_name="user_script_links")
    op.drop_index("ix_links_enabled_until", table_name="user_script_links")
    op.drop_index("ix_links_chat", table_name="user_script_links")
    op.drop_table("user_script_links")
    op.drop_table("users")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_chats_chat_id"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
